### ISSUE TITLE
有关友链页面的问题

### ISSUE THREAD

**Issue by Xunflash** [Zapic233/Matecho#3]
友链页面能否选择开启评论区呢，开启评论区可以让友链申请更方便一些。另外友链的失效头像会显示为一个错误的图像，有些丑

**Comment by KawaiiZapic** [comment]
友链页面跟文章不是通用模板, 拆出来代价太大, 考虑会做一个弹框提交友链.

**Comment by KawaiiZapic** [comment]
目前实现的做法是:
1. 游客提交友链
![image](https://github.com/user-attachments/assets/7c2c36ce-cbbe-4286-94b7-9744a7cef40c)
游客能看到右下角有一个友链申请按钮, 会弹出一个表单填写申请, 该功能是评论功能的变体, 会联动邮件插件发送通知.

2. 管理员审核友链申请手动添加
申请后管理员能在友链页面下查看待处理的友链申请:
![image](https://github.com/user-attachments/assets/b6c789cd-173c-4353-833e-31b8ef81897f)
处理完毕后回复评论, 则视作申请已处理, 不再展示该申请.  
   
如果有什么建议欢迎提出.

**Comment by Xunflash** [comment]
感谢！不过能否选择按钮位置呢，我装了一个看板娘插件有一些遮挡问题😋

**Comment by KawaiiZapic** [comment]
> 感谢！不过能否选择按钮位置呢，我装了一个看板娘插件有一些遮挡问题😋

我的建议是把看板娘挪到左边, 因为看板娘不需要点只需要看, 操作按钮放右边会更顺手
